### ISSUE TITLE
New Data?

### ISSUE THREAD

**Issue by cjo1pal** [5e-bits/5e-database#103]
There is a lot of other data for monster, classes, races, etc. for dnd. 
Are you planning on adding this data to database?
Would it be ok if I submitted pull requests for new data added?
-------I know it won't work with the API, but at least it can be in the database

**Comment by ogregoire** [comment]
What data are you speaking about? Everything published in Volo's Guide to Monsters for instance? Or Xhanatar's Guide to Everything?

Those are books that contain proprietary content. This repo provides the SRD in a convenient format. The SRD is a part of D&D that is freely (as in free speech) available to everyone, so this repo was made on that assumption. Adding new faces monsters and such that aren't present in the SRD cannot be done if the data comes from proprietary sources such as D&D books.

So, no, it would not be OK to add that data.

**Comment by JonesiBlitz** [comment]
Free speech? Hahaha

**Comment by benjaminapetersen** [comment]
Agree, this should stay strictly SRD for all kinds of copyright reasons.

On that, anyone know where the original data came from?  I'm how these JSON files were first generated.

**Comment by bagelbits** [comment]
You'd have to ask @adrpadua, though they are difficulty to get a hold of.

**Comment by benjaminapetersen** [comment]
Not sure if he is still interested in owning this repo, or if the "primary" status could be moved to someone more actively maintaining (@bagelbits& @ogregoire seem reasonable candidates as the majority of recent PRs are theirs)

**Comment by bagelbits** [comment]
I'll ask him.

**Comment by bagelbits** [comment]
So sounds like I might be getting the API and database repos transferred to me. However, this also means that the current API is going to be taken down and I'll have to host the site myself.

**Comment by benjaminapetersen** [comment]
I don't know if there is anyone depending on the current running site or if that matters.

I imagine it would self-host via github pages, its all front-end files at this point.  Just thinking out loud.

**Comment by bagelbits** [comment]
I'm going to see if there is any traffic running on the page. But spinning up my own version shouldn't be too bad. Especially if I snag the domain as well.

**Comment by bagelbits** [comment]
Closing  since both repos have been transferred.
