### ISSUE TITLE
Non-SRD monsters should be removed

### ISSUE THREAD

**Issue by ogregoire** [5e-bits/5e-database#112]
A few monsters are present in the database but should be removed.

So far I could only spot the Ancient Blue Dracolich, but I suspect more are present. I'll check this deeper in the following days.

**Comment by Alex-frazer** [comment]
what's the reason for why they need to be removed?

**Comment by ogregoire** [comment]
@Alex-frazer Because they're part of the MM, which is entirely proprietary. Only the SRD is subject to the OGL which allows us to put that data in this project. If it's in the SRD, we can put it here. If it's in any other D&D publication, we may not because of copyright laws.

**Comment by bagelbits** [comment]
I really hate that this is a thing but yeah you're right. @ogregoire If you're going to do this, can you updated the README to say something about things only subject to OGL, which is mostly just SRD?

**Comment by benjaminapetersen** [comment]
Agree, for legal reasons anything not explicitly SRD should not be included.  The repo should be canonical only.

Now, there is nothing stopping people from forking the repo and adding their own separate JSON files of the same format with homebrew, etc. monsters.

**Comment by benjaminapetersen** [comment]
Seems documents like this could be helpful for understanding legal requirements:

https://github.com/benjaminapetersen/open5e-api/blob/master/data/creature_codex/document.json

**Comment by benjaminapetersen** [comment]
Also Roll20 seems to do well with SRD content.  They have a number of public repos, such as https://github.com/Roll20/roll20-api-scripts.

But I don't know where they get their data.

**Comment by benjaminapetersen** [comment]
Referencing issue #114 as a possible way to verify before changes.
