### ISSUE TITLE
Creds left in code

### ISSUE THREAD

**Issue by pecord** [5e-bits/5e-database#12]
I was able to connect to the database that drives - http://www.dnd5eapi.co/

I dropped classes and the API no longer returned classes, I restored the collection.

**Comment by bagelbits** [comment]
That sounds like an issue with https://github.com/adrpadua/5e-srd-api?

**Comment by adrpadua** [comment]
hey thanks a lot for pointing this out. So I've dropped off this repo as it was just a chill personal project from my college years :/ (shoutout to @bagelbits for taking over)

However I do want to set up some CI/CD on Azure so that'll happen sometime before summer.
