### ISSUE TITLE
Add a Discord server for developlment chat

### ISSUE THREAD

**Issue by bagelbits** [5e-bits/5e-database#123]
@ogregoire @Alex-frazer @benjaminapetersen
I was going to add a Discord Server to coordinate some stuff because things are probably about to go bananas between the two repos and it would nice to talk to y'all about some API related stuff outside of Github Issues. I'll add a link in the README.

**Comment by benjaminapetersen** [comment]
Totally up to you!  I have no issue with github issues (ha).

**Comment by bagelbits** [comment]
I set it up just to have as a side chat. Especially since I'll be having to do things that don't fall into a direct issue of this or the API.
