### ISSUE TITLE
Class levels should not return subclass features

### ISSUE THREAD

**Issue by DFreds** [5e-bits/5e-database#152]
(Discussed on the Discord)

The URLs like 'classes/barbarian/levels/7' should not be returning specific features of the berserker primal path such as as it is a choice made at level 3. 

It doesn't make sense that the barbarian class itself would know about the specific primal path features.

Also, while I used barbarian as an example, it applies to all of the classes for their subclass feature levels.

**Comment by bagelbits** [comment]
I think that sounds reasonable, however, I think this is an issue with the [API](https://github.com/bagelbits/5e-srd-api) and not the underlying database. (I think we already discussed that on Discord).

**Comment by DFreds** [comment]
I'm looking at the JSON for the levels, and it seems like it's an issue with the database.

**Comment by bagelbits** [comment]
Oh! Interesting.

**Comment by DFreds** [comment]
I think this was solved by #153. I definitely removed the cases I found so I'll close it
