### ISSUE TITLE
Page numbers for monsters

### ISSUE THREAD

**Issue by howdoicomputer** [5e-bits/5e-database#154]
Noticed they were missing.

**Comment by ogregoire** [comment]
You really want the SRD page in the monster description?

**Comment by bagelbits** [comment]
@howdoicomputer Do you mean the SRD page number or the page number in the Monster Manual?

**Comment by howdoicomputer** [comment]
Well, I noticed that spells have PHB page numbers as part of their structure where monsters do not. I think the Monster Manual page references would be most apt. It's helpful to have the page numbers so that you can validate that the API data is correct during a session.

I wouldn't mind submitting PRs to bring up parity. It's just something I noticed; I'm not hung up on them not being there. I'm working on a project to use the API to generate Emacs org mode documents as part of running a campaign.

**Comment by bagelbits** [comment]
@howdoicomputer I think that makes sense to bring parity for that. If you want to go the extra mile, a shape like this might be better:
```
{
  title: "Monster Manual",
  page: 5
}
```

I will, however, note that the SRD monsters which are in this API can have some slight difference compared to what's in the MM. Mainly this will come across as spells. I've noticed a few spells that exist in normal 5e that are not a part of the SRD.

**Comment by bagelbits** [comment]
What's the issue with just one PR that has multiple commits so you don't have to do everything in one go? That's how I've handled other things like this.

**Comment by ogregoire** [comment]
I wouldn't go that route of putting page numbers at all in the SRD-based data. The page numbers aren't SRD-related data, but D&D-books specific. How can we check that the information is correct at a glance? We must own a version of the book. To me, this contadicts all that we did previously in cleaning the data.

If at all, you showed us that spells still contain data that should be cleaned.

**Comment by bagelbits** [comment]
> If at all, you showed us that spells still contain data that should be cleaned.

I think that might be the correct takeaway from this. Good call, @ogregoire

**Comment by bagelbits** [comment]
@ogregoire #159 That should fix it for Spells.

**Comment by bagelbits** [comment]
Closing now that page numbers have been dropped from spells.
