### ISSUE TITLE
Open Source, but which license?

### ISSUE THREAD

**Issue by ivellios** [5e-bits/5e-database#16]
Hi!

Just found your 5e API and Database. Great piece of work! And also it is great to hear you have it opened to the world. But this repo cannot be legally forked/copied/reused unless you include license file in it. 

Can you include such file? GitHub provides pre-generated files to help out.

If I reuse or share this lib, I would like to know how should I refer to you properly :)

**Comment by LouisMilotte** [comment]
Same question here, I'm currently making a project and need to know how to cite.

**Comment by ivellios** [comment]
Almost two weeks and no answer :( @adrpadua - can you provide any information on the license? We are not legally allowed even to fork it without OS License declared for your code.

**Comment by adrpadua** [comment]
Added in 1c1f04deb961b0e2e4550e0ee93bf568078c3d4c
