### ISSUE TITLE
Some subclasses missing from Levels

### ISSUE THREAD

**Issue by bagelbits** [5e-bits/5e-database#176]
Currently, we only include the subclasses for Bard and Barbarian. We're missing the SRD subclasses for everything else.

I'm not sure if we're missing these subclasses in other places as well. It's probably worth checking out.

**Comment by bagelbits** [comment]
I  believe this is only an issue in the Levels objects.

**Comment by fergcb** [comment]
In addition to ensuring there are Level objects for all Subclasses, Subclass objects should not have `features` arrays, and instead should reference the Levels resource for the subclass, as the Level objects should reference the features gained itself.

I'm happy to lead the charge on this one.
