### ISSUE TITLE
Some higher levels descriptions are lopped into the spell descriptions

### ISSUE THREAD

**Issue by ragnork2** [5e-bits/5e-database#178]
The issue seems to be predominantly in cantrips. If you look at eldritch blast, it has a higher levels description, however if you look at spells like sacred flame the descriptions are placed into the normal spell descriptions.

**Comment by bagelbits** [comment]
@ragnork2 Are there any others besides Eldritch Blast or can I close out this issue?

**Comment by ragnork2** [comment]
Im not sure, but I'll just submit a pr if I spot any others
