### ISSUE TITLE
Wrong ability score name for acrobatics

### ISSUE THREAD

**Issue by surfingolas** [5e-bits/5e-database#18]
In the ability score library for acrobatics sub 'name' it shows 'STR' when it should be 'DEX'  if I am not mistaken
{"_id":"58f40b8dc9e7ce9f72153252","index":1,"name":"Acrobatics","desc":["Your Dexterity (Acrobatics) check covers your attempt to stay on your feet in a tricky situation, such as when you’re trying to run across a sheet of ice, balance on a tightrope, or stay upright on a rocking ship’s deck. The GM might also call for a Dexterity (Acrobatics) check to see if you can perform acrobatic stunts, including dives, rolls, somersaults, and flips."],"ability_score":{"url":"http://www.dnd5eapi.co/api/ability-scores/1","name":**"STR"**},"url":"http://www.dnd5eapi.co/api/skills/1"}

**Comment by bagelbits** [comment]
Oh heck, you're right!

**Comment by bagelbits** [comment]
Fixed in #54
