### ISSUE TITLE
Add language descriptions from races to languages

### ISSUE THREAD

**Issue by Rarst** [5e-bits/5e-database#180]
Currently languages have no descriptions, however descriptions of languages are available in race information.

E.g. Elf race says:
> You can speak, read, and write Common and Elvish. Elvish is fluid, with subtle intonations and intricate grammar. Elven literature is rich and varied, and their songs and poems are famous among other races. Many bards learn their language so they can add Elvish ballads to their repertoires.

These descriptions seem like they would make sense added to languages as well.

**Comment by ogregoire** [comment]
Indeed, that's a good idea.

For reference, in the SRD:

* Dwarvish is on page 3
* Elvish is on page 4
* Halfling is on page 5
* Draconic is on page 6
* Gnomish is on page 6
* Orc is on page 7

Other languages are mentioned but not described, such as most exotic languages, or even Common (what is mentioned is that *humans* speak Common with an accent related to their other languages, not that Common comes with an accent).

Therefore we need to keep in mind that the description here is optional.

**Comment by Rarst** [comment]
I can work on PR. :)

1. What should the field name be, `desc` ?
2. Should languages without one omit the field or have `null` value for it?

**Comment by ogregoire** [comment]
> I can work on PR. :)

Great!

>     1. What should the field name be, `desc` ?

Same as the description for other things: `desc`.

>     2. Should languages without one omit the field or have `null` value for it?

They should be omitted, just like other fields in other various texts.

But please, please, make sure to take the text/data from the SRD.

**Comment by Rarst** [comment]
> They should be omitted, just like other fields in other various texts.

Gotcha, think I saw `null`s somewhere so double checking.

> But please, please, make sure to take the text/data from the SRD.

I was going to just take from the strings already in API data for races, should I double check with original SRD source?

**Comment by ogregoire** [comment]
> I was going to just take from the strings already in API data for races, should I double check with original SRD source?

Just not from the PHB. If we have it here already, it seems a good source.

**Comment by bagelbits** [comment]
Nice! Thank you for doing this! :D
