### ISSUE TITLE
Gnome race traits duplicated on Rock Gnome subrace

### ISSUE THREAD

**Issue by Rarst** [5e-bits/5e-database#184]
Rock Gnome has Darkvision and Gnome Cunning traits listed:

https://github.com/bagelbits/5e-database/blob/d3ff744c6e03a31074790e6ee195981e3893a34b/src/5e-SRD-Subraces.json#L244-L251

Per SRD these are Gnome race traits, they are not specific to the Rock Gnome subrace.

Gnome race data does have them too.

**Comment by bagelbits** [comment]
That seems like something that should be removed from the subrace since it's redundant.
