### ISSUE TITLE
Should traits data list subraces for race traits?

### ISSUE THREAD

**Issue by Rarst** [5e-bits/5e-database#186]
Currently traits data includes _subraces_ on traits granted by _race_.

E.g. Darkvision lists both Elf race and High Elf subrace, while it is specifically _Elf race_ trait.
https://github.com/bagelbits/5e-database/blob/6d2d9230d6aac2a8adeb4eae62d07a55aca3b7a8/src/5e-SRD-Traits.json#L3-L39

This is not mirrored in reverse, High Elf subrace data does not include Darkvision.

Is this intentional or makes sense to correct trait data to what specifically grants it?

It is not wrong in a sense "High Elf has Darkvision" but it is wrong in a sense "High Elf grants Darkvision".

Related #184

**Comment by bagelbits** [comment]
I think it probably makes sense to correct the trait data to what specifically grants it?

**Comment by ogregoire** [comment]
Darkvision is granted by where it is granted. A subrace contains all that the race has, except what is explicitly removed.

So let's follow the SRD and remove subraces when the subrace doesn't explicitly grant it.

On a side-note, Tiefling has darkvision but it is not shown in the traits file.

**Comment by bagelbits** [comment]
Awesome! Hey @Rarst, do you feel up to making some PRs for the three issues that you've opened? If not, I can try and tackle them.

**Comment by Rarst** [comment]
I jumped to other stuff at the moment, from the pet project I was poking this for. So probably not immediately, but whenever I circle back to that. :) If you leave these open I will get to it eventually.

**Comment by Rarst** [comment]
Status update - my DnD playing folded for the moment, so not actively working on my pet project and these by extension. :(
