### ISSUE TITLE
Ammunition weight mismatches

### ISSUE THREAD

**Issue by Rarst** [5e-bits/5e-database#189]
Equipment data lists ammunition cost per item, but weight seems to have been left per–pack.

E.g. a single arrow costs 5 cp, but 1 lbs is the weight of 20 arrows pack, not a single one.

https://github.com/bagelbits/5e-database/blob/6d2d9230d6aac2a8adeb4eae62d07a55aca3b7a8/src/5e-SRD-Equipment.json#L1713-L1724

**Comment by bagelbits** [comment]
Honestly, that seems kind of weird the way that it is. It makes more sense to have it show a pack 20 and it costs 1gp for 20? If that's possible?

**Comment by ogregoire** [comment]
The SRD says the following:

| Item | Cost | Weight
|---|---|---|
| Arrows (20) | 1 gp | 1 lb. |

It's rather clear that it's the lot of 20 that costs 1 gp and that weighs 1 lb. We must keep that data as is.

Therefore, there should be a change in the data structure: a `quantity` property should be added and be set to 20 for the arrow. We can make it optional, but then it should be clear that the default should be 1, not 0.

```
 { 
   "index": "arrow", 
   "name": "Arrow", 
   "equipment_category": "Adventuring Gear", 
   "gear_category": "Ammunition",
   "quantity": 20,
   "cost": { 
     "quantity": 1, 
     "unit": "gp" 
   }, 
   "weight": 1, 
   "url": "/api/equipment/arrow" 
 }, 
```

**Comment by bagelbits** [comment]
Excellent! I think that makes a lot of sense.
