### ISSUE TITLE
?name= searches are not displaying the same information they claim to on Try It Now

### ISSUE THREAD

**Issue by JohnWhy** [5e-bits/5e-database#192]
Searches on Try It Now appear like they should work and display only the relevant items in the overall category.  However in practice, it doesn't work and gives the entire spells list when doing partial search on name.

https://i.imgur.com/DebNUza.png
https://i.imgur.com/JJBPECi.png
https://i.imgur.com/aWUwYkQ.png

Maybe I have a fundamental misunderstanding on the usage here, but this seems like something that should be fixed.

**Comment by bagelbits** [comment]
You'd probably want to open this issue with the [API repo](https://github.com/bagelbits/5e-srd-api) instead. However, I'm not able to reproduce the issue. The Try It Now should work the exact same as going to the page. And when I use the [name query](https://www.dnd5eapi.co/api/spells/?name=Acid+Arr), I get the expected return:
```
// 20200526105231
// https://www.dnd5eapi.co/api/spells/?name=Acid+Arr

{
  "count": 1,
  "results": [
    {
      "index": "acid-arrow",
      "name": "Acid Arrow",
      "url": "/api/spells/acid-arrow"
    }
  ]
}
```

I'm sorry that I'm unable to reproduce your issue. These queries are also covered under the integration tests and wouldn't deploy unless they passed. I might suggest asking around in #help in the Discord to see if someone might be able to help you.
