### ISSUE TITLE
Lich HP are incorrect.   18d8 vs 18d8+54

### ISSUE THREAD

**Issue by Illydth** [5e-bits/5e-database#206]
Lich HP are listed as 18d8 vs. 5eSRD which is 18d8 + 54.

**Comment by AndruC** [comment]
The listing `18d8` under the lich is correct. The value, 18d8 is the monster's hit _dice_, not HP. Hit points are stored elsewhere. The db intentionally doesn't include bonus hp since this is just derived from the creature's constitution score.
