### ISSUE TITLE
Kobold HP Cannot be Calculated Correctly from JSON (See Issue 206)

### ISSUE THREAD

**Issue by Illydth** [5e-bits/5e-database#208]
I apologize for this, and I understand what you've said in #206 (with the Lich HP and Bonus HP calculation), however, that methodology (with HD being the only thing provided and CON bonus being how to calculate bonus HP), leaves us unable to properly calculate the HP on a Kobold.

A Kobold's HP Calculation is 2d6 - 2 while it's constitution bonus (penalty) however is only -1.  

This means that the Kobold ends up getting an additional -1 HP that is not identified anywhere within the JSON since there is no HP Calculation field defined within the monster JSON.

**Comment by Illydth** [comment]
Sorry, realized that -1 x 2 HD would be the appropriate calculation, sorry.

**Comment by bagelbits** [comment]
It's okay! :D
