### ISSUE TITLE
Data Issue: 5e Ancient Red Dragon Breath Weapon Damage Type listed as Bludgeoning.

### ISSUE THREAD

**Issue by Illydth** [5e-bits/5e-database#217]
The listed damage type in the JSON for the Ancient Red Dragon's breath weapon (weapon: Fire Breath) is damage type bludgeoning.

I validated against ancient-black-dragon, adult-black-dragon and adult-red-dragon, all of those types are listed correctly (acid / fire) whereas Ancient Red is listed as bludgeoning.

**Comment by bagelbits** [comment]
Well. That's awkward.
