### ISSUE TITLE
Ice Mephit - Potential Issue with Innate Spellcasting.

### ISSUE THREAD

**Issue by Illydth** [5e-bits/5e-database#222]
So there's a VERY significant difference between the Ice Mephit and Drow with regards to the "Innate Spellcasting" ability.

In the Drow's JSON data, Innate Spellcasting turns into a full spell block with a "spellcasting" block listing DC, Affecting Ability Score and a full "spells" block.

Conversely the Ice Mephit's "Innate Spellcasting" block is exceptionally limited.  There is no "spells" block, the only identifier for what spell the Mephit can cast is in the description of the Innate Spellcasting block itself (so no way to programmatically pull that out) and the whole block is missing everything the drow block has.  Usage is up 2 levels in the chain from the Drow's side:

Drow:  Innate Spellcasting -> spellcasting -> spells -> usage
Ice Mephit:  Innate Spellcasting -> usage

Is this intended?

**Comment by bagelbits** [comment]
It is not and should be fixed. Ice Mephit should follow the same structure as Drow.
