### ISSUE TITLE
Proficiencies should container a pointer to the referenced resource

### ISSUE THREAD

**Issue by dgoetsch** [5e-bits/5e-database#223]
Given a proficiency, I should be able to look up the referenced resource.

There should be an additional field on the proficiency resource:

```
"references": [{
  "name": "Dagger",
  "type": "equipment",
  "url": "/api/equipment/dagger"
}]
```

Examples:
* [the daggers proficiency](https://www.dnd5eapi.co/api/proficiencies/daggers) should contain a reference to [the dagger equipment](https://www.dnd5eapi.co/api/equipment/dagger)
* [the martial weapons proficiency](https://www.dnd5eapi.co/api/proficiencies/martial-weapons) should contain a reference to the [martial weapons equipment category](https://www.dnd5eapi.co/api/equipment-categories/martial-weapons)
* [the acrobatics proficiency](https://www.dnd5eapi.co/api/proficiencies/skill-acrobatics) should contain a reference to the [acrobatics skill](https://www.dnd5eapi.co/api/skills/acrobatics)

**Comment by dgoetsch** [comment]
I'll take this one, but can't assign to myself

**Comment by bagelbits** [comment]
Assigned to you! Also, closing out since you did an awesome job of handling it!
