### ISSUE TITLE
Missing Subraces

### ISSUE THREAD

**Issue by Zed2XS** [5e-bits/5e-database#231]
It appears only the one of the subraces of many (all?) of the races is missing.  Is this by design?

* Mountain Dwarf (basic rules & phb)
* Wood Elf (basic rules & phb)
* Stout Hafling (basic rules & phb)
* Variant Human (basic rules & phb)
* All Dragon Born Ancestries (phb)
* Forest Gnome (phb)

I'm assuming the Player's Handbook is the only non-free book you're including information from?  The inclusion of gnomes, dragonborn and tieflings seems to indicate the data is not exclusively from the basic rules.

---

I don't know if this is legal, but if you include data from other official books...

In the Sword Coast Adventurer's Guide there's dark elves (drow), gray dwarf (duergar), deep gnome (svirfneblin), half-elf variants and tiefling variants.

Mordenkainen's Tome of Foes includes 8 tiefling subraces, 6 elf subraces, gray dwarf (duergar), Gith playable race,  2 Gith subraces and deep gnome (svirfneblin).

Volo's Guide to Monsters includes 13 new playable races.  Aasimar also has the subrace "Fallen Aasimar".

I don't own every official 5e book so there are more, like Grung for example.

**Comment by fergcb** [comment]
Forgive me if I'm mistaken, but I don't think the Mountain Dwarf subrace exists in the D&D 5e SRD?

**Comment by Zed2XS** [comment]
I updated my original post when I realized a lot of subraces where missing.

Mountain Dwarf is on page 15 of[ the basic rules 2018](https://media.wizards.com/2018/dnd/downloads/DnD_BasicRules_2018.pdf).

Perhaps I don't know what SRD means?

**Comment by Zed2XS** [comment]
Ah...I wasn't aware of this.  Sorry.

### [SRD 5.1 FAQ](https://dnd.wizards.com/articles/features/systems-reference-document-srd)
Why does the SRD only have one background and one feat? Why do the PC races not include all of the subraces? The goal of the SRD is to allow users to create new content, not to replicate the text of the whole game. We encourage players, DMs, and publishers to come up with their own backgrounds and feats.

**Comment by AndruC** [comment]
It's a common misunderstanding. The Basic Rules are a superset of the SRD.
