### ISSUE TITLE
Include SRD 5.1 FAQ on Landing Page

### ISSUE THREAD

**Issue by Zed2XS** [5e-bits/5e-database#232]
I wasn't aware of the OGL and SRD and how it worked.  It appears I'm not the only one posting issues because they don't know about it either?  Consider including the first two FAQ questions on the landing page from the official SRD page to keep people like me from wasting your time? :)

Maybe something like this...

---

### Read this Before Entering an Issue

The data provided in this API is limited to what is included in the [Open Gaming License (OGL) following the Systems Reference Document (SRD) requirements](https://dnd.wizards.com/articles/features/systems-reference-document-srd).  

Many subraces, spells, magic items, monsters, etc. are not included and for legal reasons **can not** be added to this free API.

### SRD 5.1 FAQ
**Why does the SRD only have one background and one feat? Why do the PC races not include all of the subraces?** The goal of the SRD is to allow users to create new content, not to replicate the text of the whole game. We encourage players, DMs, and publishers to come up with their own backgrounds and feats.

**Why is the SRD missing some spells, magic items, and monsters?** In general, the criteria for what went into the SRD is if it (1) was in the 3E SRD, (2) has an equivalent in 5th edition D&D, and (3) is vital to how a class, magic item, or monster works. For example, the 3E SRD has the delay poison spell, but in 5th edition that's handled by the protection from poison spell, so protection from poison is in the SRD.

**Comment by bagelbits** [comment]
By landing page, do you mean this github repo, or https://www.dnd5eapi.co/?

**Comment by bagelbits** [comment]
Actually, what I might do instead is add an issue template. That would be more likely to catch this in the future.

**Comment by bagelbits** [comment]
Done!
