### ISSUE TITLE
Starting equipment arcane foci are repeated/redundant

### ISSUE THREAD

**Issue by fergcb** [5e-bits/5e-database#234]
In the Starting Equipment endpoint, every choice thats allow an Arcane focus to be chosen list the equipment items recommended by the SRD.

This raises two key issues:
1. the list is repeated several times. This means any changes to the list have to be made in several places, which is a hit to maintainability.
2. the list contains only the equipment items explicitly mentioned by the SRD as possible foci:

​
```
An arcane focus is a special item - 
an orb, a crystal, a rod, a specially constructed staff, a wand-like length of wood, or some similar item - 
designed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use such an item as a spellcasting focus.
```

The first issue could be resolved by moving the suggested arcane foci into an `arcane-foci` equipment category. This would allow easier maintenance and addition of homebrew data, and would make the choice more consistent with other starting equipment options.

The second issue is trickier; given that *any* item can be a focus, with suitable fluff to back it up, an equipment category cannot contain all possible arcane foci. The question then becomes, how likely is it that such a non-standard focus will be chosen by the user, and is that event worth supporting within the data itself, if possible?

It would be most straightforward, and most inline with the SRD source text, to offer a selection of arcane foci from an equipment category containing the items referenced in the SRD description of am arcane focus. If a user desires an alternative focus, they may swap one of the default options for another item manually, after choosing their starting equipment.

*This issue was raised after discussion on PR #230 in this [comment thread](https://github.com/bagelbits/5e-database/pull/230#discussion_r467213978)*

**Comment by ogregoire** [comment]
If I check the SRD, some classes can use an arcane focus, some other a druidic focus.

The SRD says on page 66-67 what an arcane focus can be and on page 67 what a druidic focus is, but it defines on page 69 the list of items that are available in the SRD and that are an arcane or druidic focus.

So to me, we create two new equipment categories: arcane foci and druidic foci and put into them all the items present in the tables.

Look at the table on page 65, that's where the martial melee weapons are defined. The table where the foci are is the same table except that the foci aren't weapons.

In my view it's rather clear: the page 66-67 describe the item, the page 69 is the data.

**Comment by fergcb** [comment]
@ogregoire Agreed. I think this is simply a case of moving druidic and arcane focuses into their own equipment categories, and updating the starting equipment entries to reference these.

Currently, arcane and druidic foci are simply gear categories, rather than standalone equipment categories.

**Comment by bagelbits** [comment]
Yup! That's what @fergcb and I came up with up with as well. It seems pretty straight forward.

**Comment by fergcb** [comment]
@ogregoire @bagelbits Should Holy symbols be included in this PR, too? I.e. moved to their own equipment category?

**Comment by ogregoire** [comment]
> @ogregoire @bagelbits Should Holy symbols be included in this PR, too? I.e. moved to their own equipment category?

Yes since both the cleric and the paladin use those, and get those at character creation.
