### ISSUE TITLE
Switch Adventuring Gear `gear_category` attributes to proper NamedAPIResource structures

### ISSUE THREAD

**Issue by fergcb** [5e-bits/5e-database#238]
In order to facilitate standardised linking of resources, the `gear_category` attribute of "Adventuring Gear" equipment items should use the full NamedAPIResource structure used elsewhere in the database to reference other resources.

**Comment by bagelbits** [comment]
@fergcb For the `gear_category` that are not in Equipment Category, should one be added? Ammunition comes to mind.

**Comment by fergcb** [comment]
@bagelbits That seems like a very good idea, yes!

**Comment by bagelbits** [comment]
Okay. I need to reformat, but I'll have a PR in a few minutes.
