### ISSUE TITLE
Switch to string indices for Levels

### ISSUE THREAD

**Issue by fergcb** [5e-bits/5e-database#240]
The indices should have the format `${subclass?.index ?? class.index}-${level}`.

**Examples:**
- Barbarian, level 3: `barbarian-3`
- Berserker (barb. subclass), level 6: `berserker-6`
- Monk, level 10: `monk-10`
- Way of the Open Hand (monk subclass), level 14: `open-hand-14`

**Comment by ogregoire** [comment]
What is that format, can you elaborate? I'm mostly unsure about the double question-mark `??`. Maybe provide an example of all the potential cases?

**Comment by fergcb** [comment]
It's all standard JS syntax.

`??` is the [null(-ish) coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator). 

I'll break it down:

- `subrace?.index` is `subrace.index` if `subrace` is **not** `undefined` or `null`, otherwise it evaluates to `undefined`.
- `x ?? class.index` evaluates to `x` if it is **not** `undefined` or `null`, otherwise it evaluates to `class.index`
- `${expr}` is JS string formatting syntax - any expression inside the `${}` is evaluated and interpolated into the string.

I'll add some examples to the issue body.

**Comment by ogregoire** [comment]
I'm sorry for asking to explain it, but I believe we must try to stay as much language-agnostic when it comes to the data. You seem to know JS, I'm more of a C/Java/Python/Kotlin/Go/Rust developer myself and I don't know JavaScript further than ECMAScript 3 or 4, and some notations in one language have different meanings in other languages.

**Comment by fergcb** [comment]
Yep, that's totally fair. I was asked to create this issue by @bagelbits, who used the same notation when making the suggestion, so I didn't think twice about replicating it here, especially seeing as he or I will likely be addressing this issue. It's also easy to forget that some people probably who work on the JSON data might not interact with the JavaScript elements of this database, or the API that exposes this data.

In future, I'll try to go into more depth, and to explain in more language-agnostic terms.

It may be useful to think of JS's `??` as equivalent to `?:` in Kotlin, and roughly equivalent to Python's `or` in behaviour, if my previous explanation didn't do the trick.

**Comment by ogregoire** [comment]
Indeed, I don't touch the JavaScript at all in my app: I only use the JSON files. I have to say that in that regards, I'm a bit selfish: I only see the data changes and nothing but the data changes. Everything that's JavaScript, I leave it out when updating my project with the data from here.

**Comment by bagelbits** [comment]
@fergcb If you pick this up to do, you'll also need to update the API at the same time. Similar to what I did for Starting Equipement. However, I can take this one if you don't feel comfortable touching the API.

**Comment by fergcb** [comment]
I can have a crack at it. I'll just need some time to familiarise myself with the API codebase. If I can't handle it, I'll let you know :)

**Comment by bagelbits** [comment]
@fergcb I'm pretty sure you'll just have to do exactly what I did in my last API PR but in the levels files instead. Should be straight forward but I can help out if you want.

**Comment by fergcb** [comment]
I don't expect it to be too troublesome. I'll have a look in the morning.
