### ISSUE TITLE
Cleanup Levels and Features

### ISSUE THREAD

**Issue by ogregoire** [5e-bits/5e-database#241]
Actions for the cleanup:

- [x] Use the actual feature names (`"Expertise"` instead of `"Choose: Expertise 1"`, maybe with an indicator `"Expertise (1)"`, to be discussed)
- [ ] Get rid of `"feature_choices"`
- [x] Standardise the choices in the features, check for the exact text `"choose-"` (with trailing dash) in `5e-SRD-Features.json`, and make sure that there is some `"class_specific"` or `"subclass_specific"` element that refers to those, one way or another.

Previous content:

---

Here's an excerpt from the bard levels:

```
    "level": 3,
    "ability_score_bonuses": 0,
    "prof_bonus": 2,
    "feature_choices": [
      {
        "name": "Choose: Expertise 1",
        "url": "/api/features/bard-choose-expertise-1"
      }
    ],
    "features": [
      {
        "name": "Bard College",
        "url": "/api/features/bard-college"
      }
    ],
```

There is a `"feature_choice"`, here that makes no sense.

The feature itself is called "Expertise" and is always granted. Ok, the "Expertise" feature itself grants a choice, but that should be part of the feature, not part of the level.

This should be the actual JSON (or something similar):

```
    "level": 3,
    "ability_score_bonuses": 0,
    "prof_bonus": 2,
    "features": [
      {
        "name": "Expertise",
        "url": "/api/features/bard-expertise-1"
      },
      {
        "name": "Bard College",
        "url": "/api/features/bard-college"
      }
    ],
```

The feature_choice should be present if we had this 2019 Unearthed Arcana "Class Variants" present, but look at that UA, the wording is completely different and explicitly allows for feature-choice rather, unlike the SRD wording.

**Comment by fergcb** [comment]
This is similar to what I was going to suggest once #239 goes through.

> the "Expertise" feature itself grants a choice, but that should be part of the feature, not part of the level.

The choice *is* part of the feature, and this is reflected in the structure of the Feature objects, which contain a `choice` attribute. I think the reasoning behind the separate `feature_choices` attribute, in the Level objects, is to indicate which features _require_ a further choice to be made, without having to check the features to see whether they have a `choice` attribute, I guess.

I think this specific example (though there are a few similar ones), is unusual in that the options available aren't feature-like, they're skills. So in this case, it makes *even less* sense for this to be a `feature_choice`, because you're not choosing a feature - even though the data has been structured in a way that each skill expertise is wrapped in it's own feature.

So yes - I agree that we can do away with the `feature_choices` array, but I think we can go one step further and sort out the nested choices. E.g. in the example you gave, we don't need one separate feature for each skill the bard can choose - the choice should be between _skills_, not features.

I hope I'm making sense here...

**Comment by ogregoire** [comment]
Yeah, that's specific to the bard's Expertise, but now I checked this file and the features file and they're just a mess in terms of logic. I'm thinking about rewriting those entirely, but I'll wait until you're finished with #239.

It's a mess, but it's a mess I like to rewrite.

Also, the feature names are astounding:

* `"Choose: Expertise 1"`
* `"Ability Score Improvement 1"`

So the full cleaning of those two files is part of this ticket, at least in terms of names and structure.

**Comment by bagelbits** [comment]
@ogregoire #239 has been merged in so you're clear to work on this!

**Comment by ogregoire** [comment]
Is it okay if I create a new file `Feature-Options`? Some options are referenced by several classes, such as expertise referenced by both Bards and Rogue, or Fighting Style referenced by Fighter, Paladin and Ranger.

The content will be something like containers: 

````
[
  {
    "feature_option_group": "Fighting-Style",
    "name": "Archery",
    "url": ...
  },
  {
    "feature_option_group": "Fighting-Style",
    "name": "Defense",
    "url": ...
  },
  ...
  {
    "feature_option_group": "Expertise",
    "name": "Skill: Athletics",
    "url": ...
  }
  ...
  {
    "feature_option_group": "Metamagic",
    "name": "Twinned Spell",
    "url": ...
  }
  ...
]
````

Also, what about character levels? Actually, you don't get proficiency bonus based on the class level, but on based on the character level (see SRD p. 57), so that's something that needs attending.

**Comment by bagelbits** [comment]
@ogregoire I don't mind it if it makes sense, however, it will have to be exposed in the API as well.

And I'm not sure what to do about character levels. Since I think that's only necessary for proficiency bonus? Hrm.

**Comment by bagelbits** [comment]
Also, I'm pretty sure the
```
"Choose: Expertise 1"
"Ability Score Improvement 1"
```
was me and that was just so I could get the string indices to not collide. I'm 100% behind a refactor that consolidates into a better programmatic experience.

**Comment by fergcb** [comment]
I get not wanting the indices to collide, but the *names* of the Features should be 1:1 with the SRD, imo.

**Comment by ogregoire** [comment]
> I get not wanting the indices to collide, but the _names_ of the Features should be 1:1 with the SRD, imo.

Yes, that's my take too.

**Comment by bagelbits** [comment]
Y'all are not wrong and we should 100% fix it. Just giving some historical info.

**Comment by ogregoire** [comment]
Hello, I know I'm assigned this issue, but I'm currently sick for more than a month (nope, not Covid), and I will be not be better anytime soon, so I will be unable to fix this in the foreseeable future. If anyone want to take it, please be my guest. I will try to start working on this when I'm better and after I could work a bit on my personal backlog if no one has taken it.

**Comment by bagelbits** [comment]
@ogregoire Heck! I've unassigned it from you for now. Please take all the time you need to recover.

**Comment by bagelbits** [comment]
So most of this is done. Technically choice stuff is getting handled with #383. I'll throw together a quick PR to remove `feature_choices` since we don't need that anymore.
