### ISSUE TITLE
Expose the `/api/classes/${class}/spells` endpoint in the classes resource.

### ISSUE THREAD

**Issue by fergcb** [5e-bits/5e-database#250]
The list of class spells is available using the API, but isn't discoverable. Adding a `class_spells` attribute with the value `/api/classes/${class}/spells` would expose the spell list, so that the URL doesn't have to be hard-coded or computed by the client.

**Comment by bagelbits** [comment]
We should do this for subclasses too.

**Comment by fergcb** [comment]
> We should do this for subclasses too.

@bagelbits do Subclasses have a spells endpoint like classes do? `/api/subclasses/lore/spells` isn't valid (404), for example. Maybe an issue for the API repo to support that first, before the URL is added to the DB.
