### ISSUE TITLE
Wrong description of "Choose additional fighting style" feature of Champion subclass

### ISSUE THREAD

**Issue by Freedzio** [5e-bits/5e-database#259]
Hi.

It looks like description of two features kinda merged. 

Class: Fighter
Subclass: Champion
Feature: Choose additional fighting style

This is how the desc looks like:

"At 10th level, you can choose a second option from the Fighting Style class feature. Superior Critical Starting at 15th level, your weapon attacks score a critical hit on a roll of 18-20."

**Comment by bagelbits** [comment]
Weird.
