### ISSUE TITLE
Wrong data when choosing draconic origin

### ISSUE THREAD

**Issue by Freedzio** [5e-bits/5e-database#261]
Class: sorcerer
subclass: draconic
Feature: Choose dragon ancestor

In `choice` prop, there is `choose: 2`, should be `choose: 1` instead

**Comment by ogregoire** [comment]
A warlock with a draconic subclass? Do you mean sorcerer?

**Comment by Freedzio** [comment]
Yes, sorry. I have updated the content of issue
