### ISSUE TITLE
Idea: spell learning method for classes

### ISSUE THREAD

**Issue by ghost** [5e-bits/5e-database#262]
Should classes have a category/indicator for those that prepare spells (eg clerics) vs those that learn them (eg rangers)?

**Comment by fergcb** [comment]
If I'm understanding you correctly, I feel like this is covered by the class spellcasting endpoints? E.g. `/api/classes/{index}/spellcasting`.

**Comment by ghost** [comment]
Ah yes, I suppose it's indirectly covered, a field may not be really necessary then
