### ISSUE TITLE
Non-spell casting classes should not have spellcasting or spells fields

### ISSUE THREAD

**Issue by markbastian** [5e-bits/5e-database#277]
For non-spell casting classes in 5e-SRD-Classes (e.g. fighter), there currently exist two keys:
"spellcasting": {} - always an empty map. This is a url for spellcasters.
"spells": "/a/url" - This is a dead url. "/api/classes/fighter/spells", for example, links to nothing.

I suggest we remove these keys from non-spellcasting classes. I am happy to submit a PR for this.

**Comment by bagelbits** [comment]
I think that's reasonable to remove.
