### ISSUE TITLE
Half-Elf should have two non-CHA ability scores increased by 1.

### ISSUE THREAD

**Issue by ogregoire** [5e-bits/5e-database#28]
For the Half-Elf, on page 6, the SRD states:

> **Ability Score Increase.**
> Your Charisma score increases by 2, and two other ability scores of your choice increase by 1.

The part about "two other ability scores of your choice increase by 1" isn't present in the database.

**Comment by bagelbits** [comment]
What do you think might be the best way to display this? I'm not sure it will really work with how the ability score increases are currently shown in the system.

**Comment by ogregoire** [comment]
I think a selection would be best, similar to how current selection exist. The current way is kind of flawed and the next one is rather flexible. But yeah, it's not the same as what currently exist. The template can be used for other half-mandatory, half-selection templates.

    {
      "fixed": [{"ability": "CHA", "bonus": "+2"}],
      "selection": {
        "choose": 2,
        "from": [
          {"ability": "STR", "bonus": "+1"},
          {"ability": "DEX", "bonus": "+1"},
          {"ability": "CON", "bonus": "+1"},
          {"ability": "INT", "bonus": "+1"},
          {"ability": "WIS", "bonus": "+1"},
        ]
      }
    }

**Comment by bagelbits** [comment]
Would it make sense to have the bonus as a string `+1` or just as an integer? Even if you have a negative bonus, I think it would still make sense.

**Comment by ogregoire** [comment]
It would make sense, indeed. There are [several instances of choice in the repository](https://github.com/adrpadua/5e-database/search?q=choose&unscoped_q=choose) and I'd say the best is to be consistent with the rest of the repository. Abilities are usually added using integers so let's be consistent and use numbers instead of strings. I wrote that originally on my smartphone without thinking much, just trying to quickly match it with the other choices.

**Comment by bagelbits** [comment]
I think that sounds reasonable then. If you put together a PR, I'll be happy to look it over. I can't guarantee when I'll be able to make one.

**Comment by ogregoire** [comment]
Well, that's kind of the point of me raising an issue rather than putting up a PR: currently `"ability_bonuses"` maps to an array, but if I were to make those changes, it would map to either an array for all races except Half-Elf or an object for Half-Elf (and other official races outside of the SRD, such as Changeling and Kalashtar). So for the sake of consistency, there should be a switch to a different template than the current array one.

So if that's OK with you my PR will contain changes to all races.

**Comment by bagelbits** [comment]
I think it makes sense to make the change to all races. @adrpadua, any thoughts?

**Comment by bagelbits** [comment]
Actually, can you think of any examples where you can make the same stat choice twice? Or does it always have to be unique? As far as I know, you aren't supposed to for Half-Elf but I don't know if that is the general rule.

**Comment by ogregoire** [comment]
[Kalashtar](https://www.dndbeyond.com/races/kalashtar), an official race for D&D (not SRD), has CHA +1, WIS +1, Any +1 (including CHA and WIS).

**Comment by bagelbits** [comment]
I think that's fine. I meant more for where you choose multiple like Half-Elf but it would let you choose the same stat twice.

**Comment by bagelbits** [comment]
That was awesome! Thank you!
