### ISSUE TITLE
Sea Hag spellcasting does not conform to new spellcasting object shape

### ISSUE THREAD

**Issue by Redmega** [5e-bits/5e-database#286]
Sea Hags have `Shared Spellcasting (Coven Only)` as a special ability, which has spells & spell slots in its description, but does not conform to the new spellcasting array with slots, spell array, etc.

**Comment by bagelbits** [comment]
Damn. That was clearly missed.
I bet the other Hag monsters have the same issue too.

**Comment by Redmega** [comment]
You're right! I didn't notice because the other hags already had `Innate Spellcasting`. But the Sea Hag either is missing its `Innate Spellcasting` ability, or else just doesn't have it in the SRD.

All the hags `Shared Spellcasting` seem to give them access to different spells from their `Innate Spellcasting`.

**Comment by sdrewdle** [comment]
Is anyone working on this? If not, I can give it a shot. Also, it does not look like the sea hag has innate spellcasting, so that part is fine.

**Comment by sdrewdle** [comment]
Also, I'm having trouble finding anything about hag covens in the srd pdf, and the descriptions include spells that also don't seem to be in the srd like Ray of Sickness. Rays of Sickness is also not included in the spells json. Should shared spell casting even be included?

**Comment by ogregoire** [comment]
The Hag Covens rules are not part of the SRD. A simple search on the word "Coven" or "shared spellcasting" and the lack of result is proof enough. I've taken the liberty to remove those sections from the Monsters file in #312. This absence in the SRD is enough for me to close this issue. If any question remain, please reopen.
