### ISSUE TITLE
Add proficiency options to half elf

### ISSUE THREAD

**Issue by Ajhaa** [5e-bits/5e-database#292]
Half elves get two proficiencies from the skill versatility trait, which is not reflected in the api.

Should the proficiencies come from the race, or from the trait?
The dwarf race api seems to include the proficiency choice from the tool proficiency trait.

**Comment by bagelbits** [comment]
I believe this is related to #187 which no one has quite touched yet. In short, I believe what we want is in both places.

**Comment by bagelbits** [comment]
I'm going to close this in favor of #187 which has already been opened previoously if you don't mind.
