### ISSUE TITLE
Monster Data should include XP

### ISSUE THREAD

**Issue by Redmega** [5e-bits/5e-database#299]
As per bagelbits/5e-srd-api#98 XP is not strictly a simple lookup table -- XP varies for 0CR creatures based on whether or not they have any attack actions available to them.

![](https://camo.githubusercontent.com/a8a0c76a2854f46b28056024467a14a508d7b8b4/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3635363534373636373630313635333739302f3735383435373931343837353936393537362f53637265656e73686f745f32303230303932335f3233343035352e6a70673f77696474683d323330266865696768743d323536)

**Comment by txtsd** [comment]
Here's a list of 0CR monsters:
```
Awakened Shrub
Baboon
Badger
Bat
Cat
Commoner
Crab
Deer
Eagle
Frog
Giant Fire Beetle
Goat
Hawk
Homunculus
Hyena
Jackal
Lemure
Lizard
Octopus
Owl
Quipper
Rat
Raven
Scorpion
Sea Horse
Shrieker
Spider
Vulture
Weasel
```

Only these don't have a damaging action:
```
Frog
Sea Horse
Shrieker
```
Shrieker has an action called `Shriek` that says `When bright light or a creature is within 30 feet of the shrieker, it emits a shriek audible within 300 feet of it. The shrieker continues to shriek until the disturbance moves out of range and for 1d4 of the shrieker's turns afterward` so it's not an attack.

So should I do `XP: 10` for all except Frog, Sea Horse and Shrieker?

**Comment by Redmega** [comment]
According to the SRD shriekers are worth 10xp. The only 0xp monsters are Frog, Sea Horse, and Avatar of Death (A notable exception, this one has an attack but is CR-0 with 0xp as per SRD. I wonder if that's an errata? Or if it's accurate because the only way it appears is if summoned by a Deck of Many Things)

**Comment by ragnork2** [comment]
Oh i should mention that ive already been working on this

**Comment by txtsd** [comment]
> According to the SRD shriekers are worth 10xp.

You're right.


> Actually, the Avatar of Death doesn't seem to be in the ~SRD~ API. Wonder if that was on purpose (Since it can only be summoned by a Deck of Many Things) or if it's just coincidental and needs to be added in different PR.

It's missing because it's listed under Magic Items, not Monsters.

**Comment by Redmega** [comment]
Oh, good catch! Didn't notice -- Just did a search for (0 XP).

**Comment by txtsd** [comment]
I'll work on adding Avatar of Death since @ragnork2 is taking care of this.

**Comment by bagelbits** [comment]
I almost don't want to put Avatar of Death in Monsters because for Avatar of Death:
`"hit_points": "half the hit point maximum of its summoner"`
`hit_dice` is missing
`"challenge_rating": "-"`

**Comment by bagelbits** [comment]
Closing since this got merged already!
