### ISSUE TITLE
npm task `"cache:flush"` refers to nonexistent script

### ISSUE THREAD

**Issue by ecshreve** [5e-bits/5e-database#308]
Looks like the `cacheFlush.js` script doesn't exist anymore? Not sure if this is intentional, or if this script is only used in CI, but it doesn't appear in latest master.

`"cache:flush": "node scripts/cacheFlush.js"`

https://github.com/bagelbits/5e-database/blob/82aabd66056da45df58004ebc28f949ba6f12076/package.json#L9

**Comment by bagelbits** [comment]
It shouldn't exist anymore. I'll remove the reference.
