### ISSUE TITLE
Ancient White Dragon missing legendary actions in JSON

### ISSUE THREAD

**Issue by kaitlinthachuk** [5e-bits/5e-database#32]
Ancient White Dragon is at monsters/24/. Missing legendary actions should be as follows:
"legendary_actions": [
		{
			"attack_bonus": 0,
			"desc": "The dragon makes a Wisdom (Perception) check.",
			"name": "Detect"
		},
		{
			"attack_bonus": 0,
			"desc": "The dragon makes a tail attack.",
			"name": "Tail Attack"
		},
		{
			"attack_bonus": 0,
			"desc": "The dragon beats its wings. Each creature within 15 ft. of the dragon must succeed on a DC 22 Dexterity saving throw or take 15 (2d6 + 8) bludgeoning damage and be knocked prone. The dragon can then fly up to half its flying speed.",
			"name": "Wing Attack (Costs 2 Actions)"
		}
	],

**Comment by bagelbits** [comment]
Like this? #58

**Comment by bagelbits** [comment]
Added!
