### ISSUE TITLE
Cleric's shouldn't have a `spells_known` field.

### ISSUE THREAD

**Issue by fergcb** [5e-bits/5e-database#352]
Clerics "know" all of the spells in the Cleric spell list; therefore, it would make sense to ditch the `spells_known` attribute from their Spellcasting subdocument entirely.

**Comment by bagelbits** [comment]
That makes a lot of sense.

**Comment by rbmy** [comment]
@fergcb is this still an issue? When I search the cleric spell section, I am not seeing a "spells_known" attribute in the sepllcasting section.

            "spellcasting": {
		"level": 1,
		"spellcasting_ability": {
			"index": "wis",
			"name": "WIS",
			"url": "/api/ability-scores/wis"
		},
		"info": [
			{
				"desc": [
					"At 1st level, you know three cantrips of your choice from the cleric spell list. You learn additional cleric cantrips of your choice at higher levels, as shown in the Cantrips Known column of the Cleric table."
				],
				"name": "Cantrips"
			},
			{
				"desc": [
					"The Cleric table shows how many spell slots you have to cast your spells of 1st level and higher. To cast one of these spells, you must expend a slot of the spell's level or higher. You regain all expended spell slots when you finish a long rest.",
					"You prepare the list of cleric spells that are available for you to cast, choosing from the cleric spell list. When you do so, choose a number of cleric spells equal to your Wisdom modifier + your cleric level (minimum of one spell). The spells must be of a level for which you have spell slots.",
					"For example, if you are a 3rd-level cleric, you have four 1st-level and two 2nd-level spell slots. With a Wisdom of 16, your list of prepared spells can include six spells of 1st or 2nd level, in any combination. If you prepare the 1st-level spell cure wounds, you can cast it using a 1st-level or 2nd-level slot. Casting the spell doesn't remove it from your list of prepared spells.",
					"You can change your list of prepared spells when you finish a long rest. Preparing a new list of cleric spells requires time spent in prayer and meditation: at least 1 minute per spell level for each spell on your list."
				],
				"name": "Preparing and Casting Spells"
			},
			{
				"desc": [
					"Wisdom is your spellcasting ability for your cleric spells. The power of your spells comes from your devotion to your deity. You use your Wisdom whenever a cleric spell refers to your spellcasting ability. In addition, you use your Wisdom modifier when setting the saving throw DC for a cleric spell you cast and when making an attack roll with one.",
					"Spell save DC = 8 + your proficiency bonus + your Wisdom modifier",
					"Spell attack modifier = your proficiency bonus + your Wisdom modifier"
				],
				"name": "Spellcasting Ability"
			},
			{
				"desc": [
					"You can cast a cleric spell as a ritual if that spell has the ritual tag and you have the spell prepared."
				],
				"name": "Ritual Casting"
			},
			{
				"desc": [
					"You can use a holy symbol (see Equipment) as a spellcasting focus for your cleric spells."
				],
				"name": "Spellcasting Focus"
			}
		]
	}`

**Comment by bagelbits** [comment]
@rbmy This is specifically in the Class Levels:
```json
    "features": [
      {
        "index": "spellcasting-cleric",
        "name": "Spellcasting: Cleric",
        "url": "/api/features/spellcasting-cleric"
      },
      {
        "index": "divine-domain",
        "name": "Divine Domain",
        "url": "/api/features/divine-domain"
      },
      {
        "index": "domain-spells-1",
        "name": "Domain Spells",
        "url": "/api/features/domain-spells-1"
      }
    ],
    "spellcasting": {
      "cantrips_known": 3,
      "spells_known": 4, <=========
      "spell_slots_level_1": 2,
      "spell_slots_level_2": 0,
      "spell_slots_level_3": 0,
      "spell_slots_level_4": 0,
      "spell_slots_level_5": 0,
      "spell_slots_level_6": 0,
      "spell_slots_level_7": 0,
      "spell_slots_level_8": 0,
      "spell_slots_level_9": 0
    },
```
