### ISSUE TITLE
Dragonborn Breath Weapon

### ISSUE THREAD

**Issue by GeraldTo** [5e-bits/5e-database#364]
Under races/dragonborn there's the attribute trait options which stores an array of all the dragon ancestry options however it only stores the name of the ancestry type. it doesn't hold the damage type nor the saving throw, now the distance which I believe is relevant data. Here's my suggestion on formatting (sorry idk how to format json on here):
```json
{
   "index": "black",
   "name": "Black",
   "damage_type": "Acid",
   "saving": "dex",
   "range": "5 by 30 ft. line"
}
```

**Comment by bagelbits** [comment]
FTFY

**Comment by bagelbits** [comment]
I know this is something that has come up before. Dragonborn is definitely in a weird state. Since you are given ancestry, breath weapon, and damage resistence, but you also have to pick breath weapon too?

Frankly, if I had my way, I'd split up ancestry, breath weapon, and damage resistence into all 3 choices and then you choice sets of 3.

**Comment by GeraldTo** [comment]
> I know this is something that has come up before. Dragonborn is definitely in a weird state. Since you are given ancestry, breath weapon, and damage resistance, but you also have to pick breath weapon too?

I thought the breath weapon and damage resistance are determined by the dragon type so wouldn't it still be one but just with more attributes?

**Comment by bagelbits** [comment]
Sort of? You could do it that way. My thought is following a similar approach to Multiattack in monsters. For example, you do the ancestry, breath weapon, and damage resistance for Red Dragon as one choice.
And in traits you would have "Dragon Ancestry - Red", "Breath Weapon - Red", and "Damage Resistance - Red". And then repeat this for all the other dragon types. On the Dragonborn race side, you'd remove everything from `traits` and move everything to `trait_options`.

**Comment by bagelbits** [comment]
And that would open you to do whatever data modeling you want to do for breath weapons, damage resistance, and ancestry.

**Comment by GeraldTo** [comment]
I just see it as unnecessary to separate them into sets of three since for the part people would go for the weapon and resistance associated with the ancestry.  I still see a value in keeping the current traits but I do see it as redundant to have urls to breath weapons for each index

**Comment by bagelbits** [comment]
The main reason for wanting to do this is that both breath weapon and damage resistance are linked to the ancestry a player chooses and that data is all contained in one table.

**Comment by GeraldTo** [comment]
Maybe I'm just not understanding what you're just saying because won't they be linked if they are within the same index instead of 3 different ones

**Comment by radkostanev** [comment]
I like @GeraldTo's idea of simply utilizing the existing trait_options, which right now are essentially redundant. After all picking an ancestry sets both your resistance type and breath details so in this regard it would make sense to go this way. 
On the other hand splitting the data as @bagelbits suggests might have its benefits in the long run but it might take a bit more planning.

**Comment by bagelbits** [comment]
> Maybe I'm just not understanding what you're just saying because won't they be linked if they are within the same index instead of 3 different ones

Yeah I think we're mostly on the same page but explaining things is hard. I'll put together an example a little later of what I'm thinking.

**Comment by bagelbits** [comment]
Think this has actually been handled now in a better way. Closing for now.
