### ISSUE TITLE
Cleric Starting Equipment

### ISSUE THREAD

**Issue by GeraldTo** [5e-bits/5e-database#370]
Under classes/cleric Holy Symbols is under starting_equipment_options when it should be under starting_equipment

Same logic with Druid's Druidic Foci, Paladin's Holy Symbols, and Warlock's simple weapons

**Comment by ogregoire** [comment]
You have a choice of one holy symbols among a category of holy symbols, so it seems to me that it's where it needs be.

**Comment by bagelbits** [comment]
@ogregoire Has the right of it. Arcane Focus, Druidic Focus, and the simple weapons choice for Warlock is treated the same way as well.

That being said, the choice structure that we use in this DB is maybe not the best and could use some love. But if we want to discuss that here, I'd rather have that open a separate issue. (I know there has been some discussion of it on Discord)
