### ISSUE TITLE
Invalid weapon ranges

### ISSUE THREAD

**Issue by jrasche** [5e-bits/5e-database#39]
It seems that this commit removed the correct ranges for ranged weapons and replaced them all with melee stats.
https://github.com/adrpadua/5e-database/commit/e05a87387c4abfa419079494c0748369fbe14612#diff-3020366f2048c53f42ed3e0dc6549dbaL280

This seems like it had to be a conscious decision. Was it?

**Comment by bagelbits** [comment]
That seems like a mistake.

**Comment by bagelbits** [comment]
If you want to put up a PR to revert the changes on ranged weapons, I'll happily take a look.

**Comment by bagelbits** [comment]
Fixed if you want to double check before I merge it in.
