### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by noorjano** [5e-bits/5e-database#409]

**Comment by noorjano** [comment]
@fergcb

**Comment by fergcb** [comment]
Hey..?

I'm assuming this was an accident? If you've spotted a bug, or have a feature request, feel free to open an issue about it, but make sure to include all the details in the body of the issue!

If you just want to chat, you can join us in our [Discord server](https://discord.gg/amrFrVQyBs) :)

**Comment by bagelbits** [comment]
👋🏼
