### ISSUE TITLE
-1 level spells?

### ISSUE THREAD

**Issue by absolutejam** [5e-bits/5e-database#41]
Howdy!

First of all, great work on this. I'm messing around with a small Clojure project to parse this info and I'm glad somebody has done the hard work for me 👍 

Just curious - the following spells have a spell level of `-1` - Is this correct?
  - Druidcraft
  - Fire Bolt
  - Poison Spray
  - Spare the Dying
  - Vicious Mockery

Regards,
James.

**Comment by Tenari** [comment]
yeah this is bizarre to me

**Comment by bagelbits** [comment]
Looks like those are all cantrips and their spell level should be 0.

**Comment by bagelbits** [comment]
Fixed in #57
