### ISSUE TITLE
Proficiencies: Return object instead of single item array

### ISSUE THREAD

**Issue by SleeplessOne1917** [5e-bits/5e-database#413]
I was looking through the proficiencies collection and noticed that for every proficiency, `references` is always an array with 1 entry. Yes, I checked them all. Considering the API used to reach this database only supports reads, we don't have to worry about inserting a proficiency with multiple references.

I propose we change `references`  to `reference` and that we nix the array.

**Comment by fergcb** [comment]
Looking at this, it seems to make sense to unwrap that object.

I also notice that the references specify a `type` attribute, which isn't permitted on the APIReference type as defined in the docs, and would maybe be better off as part of the base Proficiency document. Maybe that could be resolved in the same PR as part of a wider reform?

**Comment by bagelbits** [comment]
I think those both make sense.

**Comment by bagelbits** [comment]
Left a note on the PR, but we should probably break that PR into two so we can add the new fields, wait a week or two, and then remove the old fields.

**Comment by SleeplessOne1917** [comment]
@bagelbits  Is [the breaking pull request](https://github.com/5e-bits/5e-database/pull/414) ever going to be merged?

**Comment by bagelbits** [comment]
@abias1122 There are merge conflicts that need to be resolved. I left a comment on the PR a while back. I can resolve them myself if you want though.

**Comment by SleeplessOne1917** [comment]
I can try resolving them later tonight.

**Comment by bagelbits** [comment]
Cool! I'll merge it as soon as it's resolved!

**Comment by SleeplessOne1917** [comment]
Merged.

**Comment by bagelbits** [comment]
Double merged!

**Comment by bagelbits** [comment]
@abias1122 Thank you for pointing out this still hadn't been merged. I appreciate you being on top of this.
