### ISSUE TITLE
Gnome subraces

### ISSUE THREAD

**Issue by HectorHumanes** [5e-bits/5e-database#44]
The Gnome subraces (Forest Gnome and Rock Gnome) with ID's /subraces/7 and /subraces/8 respectively are missing in the API. Can you fix it, please?

**Comment by bagelbits** [comment]
I think Rock Gnome is the only thing supported under OGL (i.e. within SRD).

**Comment by bagelbits** [comment]
If you want to throw up a PR, I'd be happy to check it but I don't know when I'll get a chance to write the change myself.

**Comment by bagelbits** [comment]
I've added Rock Gnome here: #61
