### ISSUE TITLE
Missing dragonborn trait

### ISSUE THREAD

**Issue by HectorHumanes** [5e-bits/5e-database#45]
This id is inconsistent (returns null). Took from http://www.dnd5eapi.co/api/races/5

{
url: "http://www.dnd5eapi.co/api/traits/36",
name: "Damage Resistance (Dragonborn)"
}

EDIT: After a further lookup it seems to be this url: http://www.dnd5eapi.co/api/traits/18

**Comment by bagelbits** [comment]
Fixed in #52
