### ISSUE TITLE
Url property of Character Class levels does not return valid endpoints.

### ISSUE THREAD

**Issue by zenodshin** [5e-bits/5e-database#47]
Howdy - first of all, THANK YOU for putting the work into this project - currently need to fetch/parse the data on a project I started in order to learn React/Redux and this is super convenient!

**Issue**: The `url` property values for some of the Classes resources do not seem to be valid endpoints. I have not confirmed for all endpoints but at least whats needed in my case, none of the `url` values in `class_levels` for a Character Class are valid.

For instance, say I retrieved the data for a "Fighter" class using `http://www.dnd5eapi.co/api/classes/fighter` (Side note: http://www.dnd5eapi.co/api/classes/Fighter is also not valid), the relevant part of the returned data is:

`{
        ...
	"class_levels": {
		"url": "http://www.dnd5eapi.co/api/classes/Fighter/levels",
		"class": "Fighter"
	},
	...
}`

If I make a request to the resource at `http://www.dnd5eapi.co/api/classes/Fighter/levels` from the fetched `class_levels` data to get the next batch, nothing is returned.

However, if I request `http://www.dnd5eapi.co/api/classes/fighter/levels` (Notice the lowercased path), data is successfully retrieved. So it seems that since the parent class path has to be be consistent within the resource url in order to work.

Since I am using retrieved data to make the next request, the workaround I am currently using is passing the url to a utility function to ensure lower case.

**Comment by adm7373** [comment]
Hi zenodshin! The urls will end with the id, not the name. The correct url for the Fighter class is [`/api/classes/5`](http://www.dnd5eapi.co/api/classes/5). To see what the urls are for all the entities of a certain type (races, classes, etc.), just take the id off the url, so [`/api/classes/`](http://www.dnd5eapi.co/api/classes/) for example. This will contain the names and URLs for all the classes.
