### ISSUE TITLE
Extra colon for equipment "weapon_category" key

### ISSUE THREAD

**Issue by zenodshin** [5e-bits/5e-database#48]
For all equipment that is in the"Weapon" equipment category, there's an extra colon at the end of the "weapon_category" key. Should be `weapon_category: {...category}`

Sample data fetched from http://www.dnd5eapi.co/api/equipment/3
`{
   _id: "5bce91275b7768e792017db1",
   index: 3,
   name: "Greatclub",
   equipment_category: "Weapon",
   **weapon_category:: "Simple",**  // Should be weapon_category: "Simple"
   weapon_range: "Melee",
   ...
}`

**Comment by cjo1pal** [comment]
This issue has never been fixed!
