### ISSUE TITLE
Add spells from Xanathar's Guide to Everything

### ISSUE THREAD

**Issue by MLCarey321** [5e-bits/5e-database#5]
This is one of several issues that should be opened to incorporate expanded offerings from XGE.

**Comment by MLCarey321** [comment]
I've already started working on this; please assign to me.

**Comment by AndruC** [comment]
I don't believe that the spells from XGE have been released under the OGL. If not, this wouldn't be a legal addition.

**Comment by MLCarey321** [comment]
You are correct. <sigh /> Oh well, I'll keep working on it locally and just hold off on merging if/until it comes under OGL.

**Comment by AndruC** [comment]
If that happens, this can be reopened.
