### ISSUE TITLE
Standardize use of Unicode punctuation

### ISSUE THREAD

**Issue by syntaxaire** [5e-bits/5e-database#60]
The files currently contain a mixture of ASCII and Unicode punctuation. For example, in `5e-SRD-Spells.json` the usages `can’t` and `can't` both appear. The escaped string `\"Attack that creature,\"` appears in Dominate Beast, but the Unicode double quotation marks are used with `“Attack that creature,”` in Dominate Monster.

The Unicode punctuation probably came from copying and pasting from the SRD PDF which was produced in Word from WOTC, whereas the ASCII versions have come from manual edits.

I'd like to propose a PR that would standardize the use of Unicode in the project as follows:
* Replace all Unicode single right quotation marks with ASCII apostrophe
e.g. `doesn’t` becomes `doesn't`  
The reasoning for changing these is that the ASCII apostrophe is the standard for typing English words, and the visual difference is small. Also, JetBrains IDEs do not recognize the Unicode apostrophe, making simple words like `aren’t` fail spell checking.

* Use Unicode left and right double quotation marks for all embedded quotes
e.g. `\"Attack\"` becomes `“Attack”`  
The reasoning for changing this is that the Unicode marks are already prevalent from the official SRD, and they are not required to be escaped in JSON. There is a significant visual difference between the two, and as D&D is a largely text-based game, it gives a more booklike appearance to the output.  
The downside is that most keyboards do not include the Unicode version, but I think the visual tradeoff is worth it.

**Comment by bagelbits** [comment]
I agree with your first point `Replace all Unicode single right quotation marks with ASCII apostrophe`. I think that makes a lot of sense.

To your second point `Use Unicode left and right double quotation marks for all embedded quotes`: I wonder if it actually makes sense for you to do the opposite? If we use ascii, it does make it easier to type and also you have consistency of ASCII usage for both kinds?

**Comment by syntaxaire** [comment]
I could do that, and programmatically do opening and closing quotation marks in my own application. If we convert the database to ASCII, should we also replace the Unicode em dashes, en dashes, multiplication symbols and bullet points? (Most of these code points are in the Spells file as well.)

**Comment by bagelbits** [comment]
Hmmmm. I think that might make sense. What do you think?

**Comment by syntaxaire** [comment]
Sure, converting the JSONs to pure ASCII probably wouldn't hurt. I can put in sensible conversions for em- and en-dashes like double dash and single dash, asterisks for bullets, and x for times symbol. PR will come with spelling corrections as well.

**Comment by bagelbits** [comment]
Sounds good to me!

**Comment by syntaxaire** [comment]
PR coming shortly.
This is as was discussed in the issue except that instead of replacing bullet points with asterisks, I replaced them with hyphens. The reason for this is that asterisks are used in a few places in the SRD for footnotes, like in the Archmage entry. You can get bullet points from the ASCII version by converting a newline followed by a hyphen to a bullet. Using asterisks would have converted footnotes to bullets as well.

**Comment by bagelbits** [comment]
Thank you again for doing this!
