### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by RubenJ01** [5e-bits/5e-database#66]
We use this database for lookup functions programmed into our d&d 5e discord bot, which can be found here: https://github.com/RubenJ01/rewrite. We have also pushed a fair amount of updates to the database with several corrections. We were wondering if we could set up a webhook with this repository so we can see when something changes on our discord server. Thanks in advance!

**Comment by syntaxaire** [comment]
I'm with that guy ^

**Comment by bagelbits** [comment]
Let me see what I can do.

**Comment by bagelbits** [comment]
Heck. I don't have permission to set up a webhook. @adrpadua will have to do that or give me permission. @RubenJ01 in the mean time since you're forked off of my fork and I'm one of the maintainers, I can setup a webhook on my fork for you. I'll keep this issue open until we get a webhook on the main repo.

**Comment by RubenJ01** [comment]
Alright @bagelbits thanks!
https://discordapp.com/api/webhooks/567390116134518794/-p637bityeqHST32gyRWbYEv565lHVPdr6n0UuIGTxSFPjWA9cX65zYHZV_xy0wd6Xou

**Comment by bagelbits** [comment]
Looks like you need to append `/github` to it like so:
https://discordapp.com/api/webhooks/567390116134518794/-p637bityeqHST32gyRWbYEv565lHVPdr6n0UuIGTxSFPjWA9cX65zYHZV_xy0wd6Xou/github

> To make the webhook display messages properly, it's really really really REALLY really important that you append '/github' at the end of it. Yes, like five-reallys important.

Should be set up!

**Comment by bagelbits** [comment]
I'm amused that right after I set this up, no new changes have surfaced in almost two weeks. 😅

**Comment by bagelbits** [comment]
Okay, well. I set this up properly since I own the repo now? Let me know if it doesn't work. I'm gonna close this out.

**Comment by syntaxaire** [comment]
I don't know if we need this anymore, the project is on hold. But you might want to set one up for your new discord

**Comment by bagelbits** [comment]
I mean. Technically it isn't as much as I own the project now?
