### ISSUE TITLE
Can some values be null?

### ISSUE THREAD

**Issue by ogregoire** [5e-bits/5e-database#68]
Yesterday I wanted to clean up the language file, which I did. But I noticed that in the SRD, a big line strikes through the script column of the "deep speech" language. This basically means that there is no script.

However the file https://github.com/adrpadua/5e-database/blob/master/5e-SRD-Languages.json currently contains the actual value "none". There is no indicator that there is no script: the script currently has the value "none". In my view, this is incorrect.

There are usually two alternatives to this:

* the first is to remove the field entirely. If we do that, then the file is inconsistent with other files because the key is usually present but maps to an empty value, usually an array. Check the race file: it has that behavior.
* the second alternative is to use `null`. This way all the fields are set, but the actual value is set to null, and not "none". I personally like it less than the first alternative, but it keeps the consistency with the other files and reduce the work to provide.

So in short, we have three options:

1. Keep as is, having the field set to a dummy value

        {
        	"index": 12,
        	"name": "Deep Speech",
        	"type": "Exotic",
        	"typical_speakers": ["Aboleths", "Cloakers"],
        	"script": "none",
        	"url": "http://www.dnd5eapi.co/api/languages/12"
        }

2. Remove the field, opening the door to inconsistency.

        {
        	"index": 12,
        	"name": "Deep Speech",
        	"type": "Exotic",
        	"typical_speakers": ["Aboleths", "Cloakers"],
        	"url": "http://www.dnd5eapi.co/api/languages/12"
        }

3. Change `"none"` to `null` so that the key is present, but the value effectively shows that there is no value.

        {
        	"index": 12,
        	"name": "Deep Speech",
        	"type": "Exotic",
        	"typical_speakers": ["Aboleths", "Cloakers"],
        	"script": null,
        	"url": "http://www.dnd5eapi.co/api/languages/12"
        }

In the future, it might be good to tend towards 2 for everything, but it might require too much work at once. So I strongly suggest that `null` is accepted for the time being.

**Comment by bagelbits** [comment]
Technically four options if you count:
```json
 {
 	"index": 12,
 	"name": "Deep Speech",
 	"type": "Exotic",
 	"typical_speakers": ["Aboleths", "Cloakers"],
 	"script": "",
 	"url": "http://www.dnd5eapi.co/api/languages/12"
 }
```

I'd honestly be fine with either that or `null`. Though, it looks like we're not consistent on either approach. It might be worth considering?

**Comment by bagelbits** [comment]
I think in this case, `null` makes more sense than `""`. But it is probably worth looking into the inconsistent usage elsewhere.

**Comment by bagelbits** [comment]
@ogregoire I'll throw up a quick PR for the Languages. But I ran into two other cases where we use `""` instead of `null`.

### Case 1:

```json
{
  "level_acquired": 7,
  "spell_acquisition_method": {
    "name": "level",
    "url": ""
  },
  "prerequisites": [],
  "spell": {
    "url": "http://www.dnd5eapi.co/api/spells/71",
    "name": "Death Ward"
  }
}
```

`spell_acquisition_method` has a url but that doesn't exist because we don't have it. It probably makes more sense to drop the field entirely?

### Case 2:
```json
	"subtype": "",
	"alignment": "lawful evil",
	"armor_class": 17,
	"hit_points": 135,
	"hit_dice": "18d10",
	"speed": "10 ft., swim 40 ft.",
	"strength": 21,
	"dexterity": 9,
	"constitution": 15,
	"intelligence": 18,
	"wisdom": 15,
	"charisma": 18,
	"constitution_save": 6,
	"intelligence_save": 8,
	"wisdom_save": 6,
	"history": 12,
	"perception": 10,
	"damage_vulnerabilities": "",
	"damage_resistances": "",
	"damage_immunities": "",
	"condition_immunities": "",
```
`subtype`, `damage_vulnerabilities`, `damage_resistances`, `damage_immunities`, and `condition_immunities` are often set to `""`. I wonder if it makes more sense to convert the values to `null`?

What do you think? I'd like another opinion.

**Comment by bagelbits** [comment]
Hmmm. I guess for Case 2, the fields with input look like this:
```json
"subtype": "human",
"damage_vulnerabilities": "fire",
"damage_resistances": "necrotic",
"damage_immunities": "lightning, poison",
"condition_immunities": "charmed, exhaustion, frightened, paralyzed, poisoned",
```

Which raises some other questions that I don't really want to answer right now.

**Comment by ogregoire** [comment]
For the case 2, I believe that for vulnerabilities, resistances and immunities, lists (and therefore empty lists) should be used instead of `""`.

The field `"spell_acquisition_method"` doesn't make any sense as it says how one gets a specific spell. It should better be in a `level` object that says `"new_spells"` or something similar, with the prerequisistes written there if need be.

This only leaves the `"subtype"` field, which in my view can be `null` (or absent) if the value isn't applicable.

The last two instances of `""` are in the "Scrying" spell `"desc"` field. That field can easily be rewritten.

Going the route of having optional fields would probably require a kind of [JSON Schema](https://json-schema.org/) and [JSONschema.net](https://jsonschema.net/) to keep consistency and making it easier to read and parse. Each file would have its schema, in that case.

**Comment by bagelbits** [comment]
> For the case 2, I believe that for vulnerabilities, resistances and immunities, lists (and therefore empty lists) should be used instead of `""`.

That's how I was feeling as well.

> The field `"spell_acquisition_method"` doesn't make any sense as it says how one gets a specific spell. It should better be in a `level` object that says `"new_spells"` or something similar, with the prerequisistes written there if need be.

This will probably need a bit more refinement to get right but if you want to take a stab at it, I'd love to see what you're thinking.

> This only leaves the `"subtype"` field, which in my view can be `null` (or absent) if the value isn't applicable.

I agree!

> The last two instances of `""` are in the "Scrying" spell `"desc"` field. That field can easily be rewritten.

Yeah. Should be pretty simple

> Going the route of having optional fields would probably require a kind of [JSON Schema](https://json-schema.org/) and [JSONschema.net](https://jsonschema.net/) to keep consistency and making it easier to read and parse. Each file would have its schema, in that case.

We could probably go that route but I'm not married to that idea yet. Maybe in V2. 😅

**Comment by bagelbits** [comment]
I didn't try to do these yet:
```
	"damage_vulnerabilities": "",
	"damage_resistances": "",
	"damage_immunities": "",
	"condition_immunities": "",
```
Because there are some interesting choices on wording for some of those properties.

**Comment by bagelbits** [comment]
I'm also wondering if we should do something similar for `senses` and `languages` in monsters.

**Comment by bagelbits** [comment]
@ogregoire  Yeah. I'm not sure what to do with something like this:
```
"damage_resistances": "bludgeoning, piercing, and slashing from nonmagical weapons",
```

I'm not sure if it makes sense to do one of these three things:
```
#1
"damage_resistances": ["bludgeoning, piercing, and slashing from nonmagical weapons"],
#2
"damage_resistances": ["bludgeoning from nonmagical weapons", "piercing from nonmagical weapons", "slashing from nonmagical weapons"]
#3
"damage_resistances": ["nonmagical bludgeoning", "nonmagical piercing, "nonmagical slashing"],
```

I'm leaning towards the first one just to keep it consistent with the SRD text but I could be convinced otherwise.

**Comment by bagelbits** [comment]
Even better:
```
bludgeoning, piercing, and slashing from nonmagical weapons that aren't silvered
```
😂

**Comment by bagelbits** [comment]
Oh wow:
```
"piercing and slashing from nonmagical weapons that aren't adamantine"
```

Yeah, I'm just going to go with the first one for now.

**Comment by ogregoire** [comment]
The basic idea was to cleanup which is now done.

**Comment by bagelbits** [comment]
Thank you for your help!
