### ISSUE TITLE
Subrace object is invalid

### ISSUE THREAD

**Issue by trogatog** [5e-bits/5e-database#7]
Check out "starting proficiencies" -- there's an extra colon at the end of the quoted text that needs to be removed:
`
{
"_id":"5a52bbf7559f00418e532cf8",
"index":1,
"name":"Hill Dwarf",
"race":{
    "url":"http://www.dnd5eapi.co/api/races/1",
    "name":"Dwarf"},
"desc":"As a hill dwarf, you have keen senses, deep intuition, and remarkable resilience.",
"ability_bonuses":[0,0,0,0,1,0],
"starting_proficiencies:":[],
"languages":[],
"racial_traits":[
    {
        "name":"Dwarven Toughness",
        "url":"http://www.dnd5eapi.co/api/traits/4"
    }],
"url":"http://www.dnd5eapi.co/api/subraces/1"
}`

**Comment by bagelbits** [comment]
This appears to be fixed as of #34.
