### ISSUE TITLE
Error searching for Equipment Packs

### ISSUE THREAD

**Issue by cjo1pal** [5e-bits/5e-database#85]
I might just need to php code help, but I have a website that uses this API for the data. When searching through the equipment, my results always return invalid when I search for any equipment packs, ie Explorer's pack (equipment/155 - 160). 
I also can only however search for items like Alchemist's supplies (equipment/161-177) if I copy and paste it directly from the overall list. 
The apostrophe doesn't match what the keyboard inputs. 
`{"name":"Scholar's Pack","url":"http://www.dnd5eapi.co/api/equipment/160"},{"name":"Alchemist’s supplies","url":"http://www.dnd5eapi.co/api/equipment/161"}`

**Comment by bagelbits** [comment]
This repo is just the JSON data. If you have questions about the API, please direct them here:
https://github.com/adrpadua/5e-srd-api
