### ISSUE TITLE
Data Errors

### ISSUE THREAD

**Issue by cjo1pal** [5e-bits/5e-database#86]
Aboleth is missing Charisma Score ("charisma":18)
`"strength":21,"dexterity":9,"constitution":15,"intelligence":18,"wisdom":15,"constitution_save":6,"intelligence_save":8,"wisdom_save":6`

> http://www.dnd5eapi.co/api/monsters/1

Camel travels on "ground" speed
`"speed":{"quantity":50,"unit":"ft/round"}`

> http://www.dnd5eapi.co/api/equipment/192

Mounts and Vehicles duplicated
Equpiment 201- 225 == 226 - 250

> http://www.dnd5eapi.co/api/equipment/201  ==  http://www.dnd5eapi.co/api/equipment/226

**Comment by bagelbits** [comment]
The data on that website does not reflect the data in this repo. I believe all of those have already been fixed here. You should open that issue here instead: https://github.com/adrpadua/5e-srd-api
