### ISSUE TITLE
Previously closed Issues not reflected

### ISSUE THREAD

**Issue by cjo1pal** [5e-bits/5e-database#87]
In looking through some of the recently closed issues, the database files have been updated, but when accesses the jsons through the urls, the changes are not reflected. 
#32 still missing Legendary Actions from http://www.dnd5eapi.co/api/monsters/24
#48 is still incorrect in all equipment. 
#11 is still missing Charisma score. http://www.dnd5eapi.co/api/monsters/1

**Comment by ogregoire** [comment]
This is the database, not the application that show the data. You should ask on https://github.com/adrpadua/5e-srd-api instead.
