### ISSUE TITLE
Ranger Starting Equipment

### ISSUE THREAD

**Issue by cjo1pal** [5e-bits/5e-database#91]
Here is what currently present for the Starting equipment of a Ranger.
`{
	"index": 8,
	"class": {
		"url": "http://www.dnd5eapi.co/api/classes/8",
		"name": "Ranger"
	},
	"starting_equipment": [{
		"item": { "url": "http://www.dnd5eapi.co/api/equipment/36", "name": "Longbow"}, "quantity": 1}, {
		"item": { "url": "http://www.dnd5eapi.co/api/equipment/54", "name": "Arrow"}, "quantity": 20}],
	"choices_to_make": 3,
	"choice_1": [{
		"choose": 1,
		"type": "equipment",
		"from": [{
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/43", "name": "Scale Mail"}, "quantity": 1}]
	}, {
		"choose": 1,
		"type": "equipment",
		"from": [{
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/28", "name": "Shortsword"}, "quantity": 1}]
	}],
	"choice_2": [{
		"choose": 1,
		"type": "equipment",
		"from": [{
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/156", "name": "Dungeoneer's Pack"}, "quantity": 2}]
	}, {
		"choose": 2,
		"type": "equipment",
		"from": [{
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/1", "name": "Club"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/2", "name": "Dagger"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/3", "name": "Greatclub"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/4", "name": "Handaxe"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/5", "name": "Javelin"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/6", "name": "Light hammer"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/7", "name": "Mace"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/8", "name": "Quarterstaff"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/9", "name": "Sickle"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/10", "name": "Spear"}, "quantity": 1}]
	}],
	"choice_3": [{
		"choose": 1,
		"type": "equipment",
		"from": [{
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/156", "name": "Dungeoneer's Pack"}, "quantity": 1}]
	}, {
		"choose": 1,
		"type": "equipment",
		"from": [{
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/158", "name": "Explorer's Pack"}, "quantity": 1}]
	}],
	"url": "http://www.dnd5eapi.co/api/startingequipment/8"
}`

This doesn't match the official PHB, or make sense between the choices.

- (A) scale mail or (b) leather armor
- (a) two shortswords or (b) two simple melee weapons
- (a) a dungeoneer's pack or (b) and explorer's pack
- a longbow and a quiver of 20 arrows

It should really be:
`{
	"index": 8,
	"class": {
		"url": "http://www.dnd5eapi.co/api/classes/8",
		"name": "Ranger"
	},
	"starting_equipment": [{
		"item": { "url": "http://www.dnd5eapi.co/api/equipment/36", "name": "Longbow"}, "quantity": 1}, {
		"item": { "url": "http://www.dnd5eapi.co/api/equipment/54", "name": "Arrow"}, "quantity": 20}],
	"choices_to_make": 3,
	"choice_1": [{
		"choose": 1,
		"type": "equipment",
		"from": [{
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/43", "name": "Scale Mail"}, "quantity": 1}]
	}, {
		"choose": 1,
		"type": "equipment",
		"from": [{
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/39", "name": "Leather Armor"}, "quantity": 1}]
	}],
	"choice_2": [{
		"choose": 1,
		"type": "equipment",
		"from": [{
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/28", "name": "Shortsword"}, "quantity": 2}]
	}, {
		"choose": 2,
		"type": "equipment",
		"from": [{
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/1", "name": "Club"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/2", "name": "Dagger"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/3", "name": "Greatclub"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/4", "name": "Handaxe"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/5", "name": "Javelin"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/6", "name": "Light hammer"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/7", "name": "Mace"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/8", "name": "Quarterstaff"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/9", "name": "Sickle"}, "quantity": 1}, {
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/10", "name": "Spear"}, "quantity": 1}]
	}],
	"choice_3": [{
		"choose": 1,
		"type": "equipment",
		"from": [{
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/156", "name": "Dungeoneer's Pack"}, "quantity": 1}]
	}, {
		"choose": 1,
		"type": "equipment",
		"from": [{
			"item": { "url": "http://www.dnd5eapi.co/api/equipment/158", "name": "Explorer's Pack"}, "quantity": 1}]
	}],
	"url": "http://www.dnd5eapi.co/api/startingequipment/8"
}`

**Comment by bagelbits** [comment]
Oh yeah. You're right. That is off. I'll write up a quick PR. Please note, changes here will not be reflected in the API.

**Comment by bagelbits** [comment]
@cjo1pal I've just put up a PR to fix this. Can you verify that that is what you'd expect?

**Comment by cjo1pal** [comment]
Yes this looks correct in the database!
How does the API get updated?

**Comment by bagelbits** [comment]
That’s a great question. @adrpadua?

**Comment by cjo1pal** [comment]
@bagelbits Does anyone know how the API works with the database as it looks like @adrpadua isn't actively contributing any more?

**Comment by bagelbits** [comment]
I don't think so. At least not as far as I'm aware. I think you can run your own based off of:
https://github.com/adrpadua/5e-srd-api
