### ISSUE TITLE
Chain devil has a wrong Challenge Rating

### ISSUE THREAD

**Issue by Taywee** [5e-bits/5e-database#94]
The Chain Devil's CR is listed in the json as 11, but in the actual SRD, it's 8.

**Comment by Taywee** [comment]
On checking again, there are a few other things incorrect about the Chain Devil.  The passive perception is listed as 8 instead of 11, and its saving throw modifiers aren't specified (should be Con +7, Wis +4, Cha +5).

Were these lists hand-made or generated?  If the generator has issues with things (perhaps the Bone Devil has an issue because the page wraps before the stat block), other monsters might have issues when their stat blocks aren't where expected.

edit:  On a quick lookthrough, I don't see other monsters with the same stat block column wrapping that are showing incorrect stats, at least not on a cursory look.

**Comment by bagelbits** [comment]
I'm 100% not sure how the lists were made. I assume hand-made? But really unsure since I didn't create it. I just stumbled into maintaining it 😅 .

I don't think the saving throw modifiers are specified on any monsters at this point. But it would be great to see them.

I'll spin up a quick PR with the CR and perception changes on Chain Devil though.

**Comment by Taywee** [comment]
The saving throw modifiers are specified on at least some other monsters as {attribute}_save.  See, for instance: https://github.com/adrpadua/5e-database/blob/master/5e-SRD-Monsters.json#L10706
I was looking into possibly generating the monster json from the source SRD, but the PDF isn't very parseable, unfortunately.

**Comment by bagelbits** [comment]
I've added those fixes at least.

**Comment by bagelbits** [comment]
Oh you're right, we do have the saves like that whenever we have it in the MM.

**Comment by bagelbits** [comment]
I guess it's only in there if the save is different then the base modifier. Fixed.
