### ISSUE TITLE
Race Traits contain incorrect URL

### ISSUE THREAD

**Issue by cjo1pal** [5e-bits/5e-database#99]
5e-SRD-Races.json
Some of the Racial Traits for the different races have the incorrect url associated with the name in the Traits section. 

EX:
Elf Traits
`traits": [
    {
      "url": "http://www.dnd5eapi.co/api/traits/5",
      "name": "Darkvision (Elf)"`
Darkvision is `http://www.dnd5eapi.co/api/traits/1`

**Comment by bagelbits** [comment]
Nice catch. I don't know when I'll have a chance to fix this and review all of the traits but if you want to open a PR for the fixes, I'm happy to review it.

**Comment by cjo1pal** [comment]
@bagelbits I just created that pull request for this issue. 
Now that I know how to do this I'll submit more as I find issues with the files.

**Comment by bagelbits** [comment]
Thank you for doing this! And appreciate you creating additional PRs.
